<?php

$go = @$_GET["go"];

/*$info = array("minigames" => array(
	array("id" => 0, "name" => "Maze Screamer", "thumb" => "./images/thumbs/maze.png", "type" => "Minijuego", "desc" => Lang::$lang->text["m1_desc"], "avers" => "0.0.1", "author" => "Ikillnukes", "creation_date" => "25-06-2015 14:43", "publish_date" => "26-06-2015 16:34", "other_data" => Lang::$lang->text["m1_odata"]), 
	array("id" => 1, "name" => "Hords Game", "thumb" => "./images/thumbs/hords.png", "type" => "Minijuego", "desc" => Lang::$lang->text["m2_desc"], "avers" => "0.0.0", "author" => "Ikillnukes", "creation_date" => "26-06-2015 18:26", "publish_date" => "28-06-2015 17:26", "other_data" => Lang::$lang->text["m2_odata"])
	), "assets" => array(
	array("id" => 2, "name" => "Ballistic Physics", "thumb" => "./images/thumbs/ballistic.png", "type" => "Asset", "desc" => Lang::$lang->text["p1_desc"], "avers" => "0.0.0", "author" => "Ikillnukes", "creation_date" => "16-06-2015 17:35", "publish_date" => "27-07-2015 13:58", "other_data" => Lang::$lang->text["p1_odata"]),
	array("id" => 3, "name" => "Advanced Crosshair", "thumb" => "./images/thumbs/crosshair.png", "type" => "Asset", "desc" => Lang::$lang->text["p2_desc"], "avers" => "0.0.0", "author" => "Ikillnukes", "creation_date" => "???", "publish_date" => "???", "other_data" => Lang::$lang->text["p2_odata"])));

if(isset($go) && !array_key_exists($go, $info))
{
	include(INCLUDES.'/404.php');
	die();
}

$elem = array_merge($info["minigames"], $info["assets"]);
if(isset($go) && array_key_exists($go, $info))
	$elem = $info[$go];*/

//https://scontent-mad1-1.xx.fbcdn.net/hphotos-xap1/t31.0-8/s960x960/886864_453080824892547_8774485805036172898_o.jpg
//http://stackoverflow.com/questions/2526772/search-for-string-within-text-column-in-mysql

$num_rows = Query::count('id', 'projects');

$setts = SettingsManager::get('project_settings');
$setts = isset($setts) ? unserialize($setts) : null;

if($num_rows > 0) 
{
	$arr = array();
	if(@$_GET['do'] === "search") 
	{
		$name = @$_GET['name'];
		$type = @$_GET['type'];
		$author = @$_GET['author'];
		if(empty($author) || (isset($author) && Query::count('id', 'users', "WHERE id = '$author'")))
		{
			$result = Query::run("SELECT * FROM projects");
			while($row = mysqli_fetch_assoc($result)) // loop to store the data in an associative array.
			    $arr[] = array("id" => $row['id'], "data" => unserialize($row['data']));
			if(isset($name))
				$arr = ContentUtils::searchFromSQL($arr, 'name', $name, true);
			if(isset($type))
				$arr = ContentUtils::searchFromSQL($arr, 'type', $type, false);
			if(isset($author))
				$arr = ContentUtils::searchFromSQL($arr, 'author', $author, false);
			if(count($arr))
			{
				$pages = new Paginator(count($arr), 9, isset($setts['max_entries']) ? ((int)$setts['max_entries'] === 0 ? count($arr) : $setts['max_entries']) : 10);
				$arr = array_slice($arr, $pages->limit_start, $pages->limit_end);
			}
		}
	} 
	else 
	{
		$pages = new Paginator($num_rows, 9, isset($setts['max_entries']) ? ((int)$setts['max_entries'] === 0 ? $num_rows : $setts['max_entries']) : 10);
		$result = Query::run("SELECT * FROM projects ORDER BY id ASC LIMIT $pages->limit_start, $pages->limit_end");
		while($row = mysqli_fetch_assoc($result)) 
			$arr[] = array("id" => $row['id'], "data" => unserialize($row['data']));
	}

	echo '
	<script type="text/javascript" src="./js/jquery.searchabledropdown-1.0.8.min.js"></script>
	<script>
		$(document).ready(function() {
			$("#admin_list").searchable({
				maxListSize: 100,						// if list size are less than maxListSize, show them all
				maxMultiMatch: 50,						// how many matching entries should be displayed
				exactMatch: false,						// Exact matching on search
				wildcards: true,						// Support for wildcard characters (*, ?)
				ignoreCase: true,						// Ignore case sensitivity
				latency: 50,							// how many millis to wait until starting search
				warnMultiMatch: "top {0} matches ...",	// string to append to a list of entries cut short by maxMultiMatch 
				warnNoMatch: "no matches ...",			// string to show in the list when no entries match
				zIndex: "auto"							// zIndex for elements generated by this plugin
		   	});
		});
	</script>
	<center style="margin-top:10px;">
		<div class="menu_block center" style="width: 555px;">
			<div>Buscador</div>
			<div>
				<div>
					<form>
						<table>
							<tr>
								<td>Nombre:<br><input type="text" name="name" /></td>
								<td>Categoría:<br>
									<select name="type">
										<option selected disabled></option>';
								foreach(Lang::$lang->text['projectType'] as $k => $v) 
									echo '<option value="'.$k.'">'.$v.'</option>';
								echo '
									</select>
								</td>
								<td>Autor:<br>
								<select name="author" id="admin_list">
									<option selected disabled></option>';

								$result = Query::run("SELECT id, username FROM users WHERE rank_id = '3'");
								while($row = mysqli_fetch_assoc($result))
									echo '<option value="'.$row['id'].'">'.$row['username'].'</option>';

								echo '</select>
								</td>
								<td><input type="button" style="background-image: url(./images/icons/search.png);width:31px;height:31px;position:relative;margin-top:20px;" onclick="$.redirect(location.protocol+\'//\'+location.host+location.pathname+\'?action=projects&do=search&\'+($(this.parentNode.parentNode.parentNode.parentNode.parentNode).serialize()), {\'success\':\'1\',\'msg\':\''.Lang::$lang->text["do_search"].'\',\'f\':\'true\'});" /></td>
							</tr>
						</table>
					</form>
				</div>
			</div>
		</div>';
		if(@$_GET['do'] === "search" && isset($pages))
			echo '<div style="text-align:left;width: 519px;">'.ContentUtils::str_format(Lang::$lang->text['search_results'], $pages->items_per_page > $pages->total_items ? $pages->total_items : $pages->items_per_page, $pages->total_items, $pages->current_page, $pages->num_pages).'</div>';
		echo '<div id="projects">
			<table class="listTable">';

	if(count($arr)) {
		for($i = 0; $i < count($arr); ++$i)
		{
			$data = $arr[$i]["data"][Lang::$lang->lang_name];
			echo '
				<tr>
					<td>
						<img class="game-thumb" src="'.$data["thumb"].'" />
					</td>
					<td class="mem_pres">
						<b>'.Lang::$lang->text["name"].':</b> '.$data["name"].'<br>
						<b>'.Lang::$lang->text["desc"].':</b> '.$data["desc"].'<br>
						<b>'.Lang::$lang->text["avers"].':</b> '.$data["avers"].'<br>
						<b>'.Lang::$lang->text["author"].':</b> '.UserUtils::getStat($data["author"], "username").'<br>'.
						((!isset($go)) ? '<b>Tipo:</b> '.Lang::$lang->text['projectType'][$data["type"]].'<br>' : '')
						.'<b>'.Lang::$lang->text["creation_date"].':</b> '.date('d-m-Y H:i', $data["creation_date"]).'<br>
						<b>'.Lang::$lang->text["publish_date"].':</b> '.date('d-m-Y H:i', $data["publish_date"]).'<br>
						<b>'.Lang::$lang->text["odata"].':</b> '.$data["other_data"]["odata_text"].'<br>
						<b style="font-size: 16px;"><a href="index.php?action=preview&id='.$arr[$i]["id"].'">'.Lang::$lang->text["see"][$data["type"]].'</a></b>
					</td>
				</tr>';
		}
		echo '
		</table>
		</div>
		<div id="pag">'.$pages->display_pages().'</div>';
	} else
		echo '<center><h3>No hay resultados para mostrar.</h3></center>';
	echo '</center>';
} else
	echo '<center><h3>No hay proyectos para mostrar.</h3></center>';

/*echo '
<center>
	<table style="width: 500px;word-wrap: break-word;">
		<tr>
			<td>
				<img class="game-thumb" src="./images/thumbs/ballistic.png" />
			</td>
			<td class="mem_pres">
				<b>'.Lang::$lang->text["name"].':</b> Ballistic Physics<br>
				<b>'.Lang::$lang->text["desc"].':</b> '.Lang::$lang->text["p1_desc"].'<br>
				<b>'.Lang::$lang->text["avers"].':</b> 0.0.0<br>
				<b>'.Lang::$lang->text["author"].':</b> Ikillnukes<br>
				<b>'.Lang::$lang->text["creation_date"].':</b> 16-06-2015 17:35<br>
				<b>'.Lang::$lang->text["publish_date"].':</b> 27-07-2015 13:58<br>
				<b>'.Lang::$lang->text["odata"].':</b> '.Lang::$lang->text["p1_odata"].'<br>
				<b style="font-size: 16px;"><a href="index.php?action=project&id=0">'.Lang::$lang->text["see_asset"].'</a></b>
			</td>
		</tr>
		<tr>
			<td>
				<img class="game-thumb" src="./images/thumbs/crosshair.png" />
			</td>
			<td class="mem_pres">
				<b>'.Lang::$lang->text["name"].':</b> Advanced Crosshair<br>
				<b>'.Lang::$lang->text["desc"].':</b> '.Lang::$lang->text["p2_desc"].'<br>
				<b>'.Lang::$lang->text["avers"].':</b> 0.0.0<br>
				<b>'.Lang::$lang->text["author"].':</b> Ikillnukes<br>
				<b>'.Lang::$lang->text["creation_date"].':</b> ???<br>
				<b>'.Lang::$lang->text["publish_date"].':</b> ???<br>
				<b>'.Lang::$lang->text["odata"].':</b> '.Lang::$lang->text["p2_desc"].'<br>
				<b style="font-size: 16px;"><a href="index.php?action=project&id=1">'.Lang::$lang->text["see_asset"].'</a></b>
			</td>
		</tr>
	</table>
</center>';*/